#!/usr/bin/env ansible-playbook
---
- name:         stop elasticsearch
  hosts:        elasticsearch
  gather_facts: False
  tasks:
    - name:     stop elasticsearch service
      service:
        name:   elasticsearch
        state:  stopped
