#!/usr/bin/env ansible-playbook
---
- name:  configure elasticsearch nodes
  hosts: elasticsearch
  vars:
    elasticsearch_cluster_name: demo
  roles:
    - common
    - elasticsearch
  tasks:
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined and ansible_hostname != item
      with_items: "{{ groups.elasticsearch }}"
