#!/usr/bin/env ansible-playbook
---
- name:         start elasticsearch
  hosts:        elasticsearch
  gather_facts: False
  tasks:
    - name:     start elasticsearch service
      service:
        name:   elasticsearch
        state:  started
