---
- name:         tune elasticsearch server
  import_tasks: server-config.yml

- name:         install elasticsearch
  import_tasks: install.yml

- name:         configure elasticsearch
  notify:       restart elasticsearch
  template:
    src:        elasticsearch.yml
    dest:       /etc/elasticsearch/elasticsearch.yml
    mode:       0660

- name:         enable elasticsearch
  import_tasks: service.yml
